---
title: 'Unique Devices on all Wikipedia projects'
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, tidy=TRUE, fig.path = "figures/md_figs/")
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r eval=FALSE}
query <- "
SELECT
  year, month, CONCAT(year,'-',LPAD(month,2,'0')) AS date,
  SUM(uniques_estimate) as unique_devices
FROM 
	wmf.unique_devices_per_project_family_monthly
WHERE year >= 2018
  AND project_family = 'wikipedia'
GROUP BY year, month ORDER BY year, month LIMIT 1000;
"
results <- collect(sql(query))
save(page_previews, file="Data/unique_devices.tsv")
```

```{r}
unique_devices_monthly <- read.delim("data/unique_devices.tsv", sep = "\t", stringsAsFactors = FALSE)
```

Calculate total monthly unique devices with yoy changes

```{r}
unique_devices_summary <- unique_devices_monthly  %>%
  select(-c(1,2)) %>%
  arrange(date) %>%
  mutate(unique_devices = unique_devices,
    YoY= unique_devices/lag(unique_devices,12) -1)

knitr::kable(unique_devices_summary)
```

Plot unique devices 
```{r}
p <- ggplot(unique_devices_summary, aes(x=date, y = unique_devices)) +  
  geom_col(fill= 'blue') +
  scale_y_continuous("unique devices per month", labels = polloi::compress) +
  labs(title = "Monthly Unique Devices on All Wikipedias, 2018-2019") +
  ggthemes::theme_tufte(base_size = 12, base_family = "Gill Sans") +
  theme(axis.text.x=element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        panel.grid = element_line("gray70"))

ggsave(filename="unqiue_devices_monthly.png", plot = p, path = "figures", units = "in", dpi = 150, height = 6, width = 10, limitsize = FALSE)  
p
```
